### ISSUE TITLE
Gallery TODO

### ISSUE THREAD

**Issue by soulchainer** [soulchainer/affray-devlog#13]
TODO about the gallery page:

- [x]  In Chrome, I got, in some moment, this warning:
  >  Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help, check https://xhr.spec.whatwg.org/.
  > Setting 'XMLHttpRequest.withCredentials' for synchronous requests is deprecated.

  It still works, but I want to read about this, because seems like is deprecated and better do it well.
- [x]  When you go from infinite scroll mode to paginated mode, the arrow links don't point to the correct next pages (the pages already paginated by AJAX). Look into it, and, maybe, fix it.
- [x]  In Firefox I got this warning:

  >  This site appears to use a scroll-linked positioning effect. This may not work well with asynchronous panning; see https://developer.mozilla.org/docs/Mozilla/Performance/ScrollLinkedEffects for further details and to join the discussion on related tools and features!
  Probably, this is what is causing some scroll bug I don't see in Chromium. Look into it.

**Comment by soulchainer** [comment]
Happens that the *Synchronous* `XMLHttpRequest` on the main thread is being made by Tumblr scripts, not mire, so nothing to do. I revised my `XMLHttpRequest`and I'm doing them async...
So, I just need to check the Firefox warning now.

**Comment by soulchainer** [comment]
About the Firefox warning, [in the documentation about scroll linked effects](https://developer.mozilla.org/en-US/docs/Mozilla/Performance/Scroll-linked_effects) I just read:

> In many cases, scroll-linked effects can be reimplemented using CSS and made to run on the compositor thread. However, in some cases the current APIs offered by the browser do not allow this. **In all cases, however, Firefox will display a warning to the developer console (starting in version 46) if it detects the presence of a scroll-linked effect on a page**. 

And well, happens that I listen to the `scroll` here to charge new pages with *AJAX*, so that's imposible to achiveve with CSS at all, so... Keep the warning, but this can't be changed.

**Comment by soulchainer** [comment]
Problem with pagination links coming from infinite scroll (and then disabling it) solved by PR https://github.com/soulchainer/affray-devlog/commit/6adaa6c5b7b20a61339a34a15706869931d42110
